version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-stretch
    steps:
      # 😱 An API key in plain text in the URL! 😱
      - run: curl "https://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=${APPID}"
